[client]
showSidebarNavigation = false


[theme]
primaryColor = "#8b5cf6"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#fafafa"
textColor = "#18181b"
linkColor = "#7c3aed"
borderColor = "#e4e4e7"
font = "DM Sans"
codeFont = "Fira Code"